---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-app
spec:
  interval: 5m0s
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudnative-experience-lab

