---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cloudnative-experience-lab
  namespace: flux-app
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/ThomasPause/cloudnative-experience-lab.git
