---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-test
  namespace: flux-app
spec:
  interval: 1m0s
  path: ./clusters/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudnative-experience-lab
